### ISSUE TITLE
Creating a Server Error

### ISSUE THREAD

**Issue by surtic86** [grimsi/accservermanager#4] opened 2019-04-11 10:08 UTC
Hi there,

I have installed your ACC ServerManager with your Docker Image and placed the 0.7.2 Server Exe in the right Folder (gets Recognized from your Tool). I can Access the Manager can create Events but i can't create e Server.

Now i get an Error when i click on Create. `Cant delete container 'null': path is 'null'.` 

Screenshot: https://monosnap.com/image/NcgCIM6Hl2pbOeg8DrS343Xk3Mq2tX.png

Docke Command
`
sudo docker run -d --name accservermanager --restart=unless-stopped \
-e accservermanager.folder-path=/data/acc/accservermanager \
-e accservermanager.username=TEST \
-e accservermanager.password=TEST \
-v /data/acc/db:/data/db \
-v /data/acc/accservermanager:/opt/server \
-v /var/run/docker.sock:/var/run/docker.sock \
-p 8000:8000 \
-p 9554:9554 \
grimsi/accservermanager:latest`

Thanks for your Help

**Comment by grimsi** [comment] 2019-04-11 11:03
Thanks for your report :)

I also had this issue, but only when running docker on a Windows host (thats why Windows is currently not supported).
What system are you running on?

**Comment by surtic86** [comment] 2019-04-11 11:45
Im on a Ubuntu 16.04.6 LTS

**Comment by grimsi** [comment] 2019-04-11 11:53
Okay, could you give me the logs of the container (with `docker logs accservermanager`)?
Thanks :)

**Comment by surtic86** [comment] 2019-04-11 12:22
Sure :) the Log is Quite big.... 8MB.

Removed the old Container and created a new Fresh Instance, then created a Event and tried it again with creating a Server.

You can download / view the Log from 
Plain: https://www.nonameweb.ch/stuff/acc/accservermanager.log 
Zip: https://www.nonameweb.ch/stuff/acc/accservermanager.log.zip

8749220 Apr 11 14:12 accservermanager.log
  387195 Apr 11 14:12 accservermanager.log.zip

**Comment by grimsi** [comment] 2019-04-11 12:43
Located the error:
`javax.ws.rs.ProcessingException: Error closing message content input stream.
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:162) ~[jersey-common-2.27.jar!/:na]
[...}
Caused by: java.io.IOException: Bad file descriptor
	at jnr.enxio.channels.Common.read(Common.java:67) ~[jnr-unixsocket-0.18.jar!/:na]
[...]`

Looks like my software has problems connecting to the docker deamon on your host.
Could you try to install the newest docker version ([18.09.4](https://docs.docker.com/engine/release-notes/))?

Thanks a lot for your great cooperation!
As soon as I get home I will try to reproduce your issue but I suspect that either your Ubuntu or your Docker is too old (I only tested Ubuntu 18.04 and Docker 18.09.X)

**Comment by surtic86** [comment] 2019-04-11 13:14
Yes looks like your Libry? just Supports Docker 18? On Ubuntu 16.04 is Docker 17 the newest Version form the Offical Docker Repo (https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages)

When you can't "fix" it we know now that Minimum Docker Version would be 18 :)

**Comment by grimsi** [comment] 2019-04-11 13:21
I use the spotify-docker-client to let my Java application communicate with Docker.
Theoretically this library [supports docker 17.03.1-ce and newer](https://github.com/spotify/docker-client#version-compatibility), but the README is a bit outdated.
I will try to test Ubuntu 16.04 with Docker 17 on a fresh installation so we can be sure that thats the issue.
I really hope that the fault is in my application, because that would be possible to fix for me. Otherwise I would have to set the supported Docker version to 18, which would affect many potential users :(

**Comment by grimsi** [comment] 2019-04-12 06:39
Okay, so I tested a fresh Ubuntu 16.04 installation and installed docker using [this](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-convenience-script) method:
```
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
```
The docker script automatically installed `Docker version 18.09.5, build e8ff056` on my system.
With that docker version everything runs fine (as expected).

It looks like docker changed their official repo with the release of 17.06 (according to [this article](https://medium.com/@gauravsj9/how-to-install-specific-docker-version-on-linux-machine-d0ec2d4095)), so youre using an old repository and should be able to install docker 18 by using the current one.

But I also tested it with the old repository and installed `Docker version 17.05.0-ce, build 89658be` which also works just fine.
Do you have any other software installed or did you configure anything that could possibly interfere with my application?

**Comment by surtic86** [comment] 2019-04-14 21:35
Oh interesting.... thanks i will look into that how i can now update daht save without any trouble.

**Comment by grimsi** [comment] 2019-04-15 16:40
Since I could not reproduce your error I think that the bug is related to something specific to your machine.
Therefore I will close this issue for now. If you have anything to add or questions related to this problem just reply here and I will reopen it again

**Comment by HendrikRoth** [comment] 2019-05-18 13:46
Same issue here,

Hostsystem: Ubuntu 18.04.2 LTS
Docker version: 18.09.2

**Comment by grimsi** [comment] 2019-05-18 14:06
Is it possible for you to provide log files?
That would be really great :)

> Okay, could you give me the logs of the container (with `docker logs accservermanager`)?
> 
> If you have the time it would be really great if you could delete the accservermanager container and all linked docker volumes and create the container again, but add `-e logging.level.root=debug` to the `docker run` command this time and then upload the logfile here (see [this](https://stackoverflow.com/questions/33017329/where-is-a-log-file-with-logs-from-a-container) for a explanation on how to get the logfile)?
> Thanks :)

**Comment by HendrikRoth** [comment] 2019-05-18 14:17
I would, but it worked now and i have no idea why (i only added the environment variable for debugging, but i can't believe that this changed anything this related).

But i have a new issue with the newly created container:
```wine: cannot find L"C:\\windows\\system32\\accServer.exe"```

**Comment by grimsi** [comment] 2019-05-18 14:18
Glad that it works now. Could you please open a new issue for the wine bug and attach the log files?

**Comment by surtic86** [comment] 2019-05-24 08:42
> Since I could not reproduce your error I think that the bug is related to something specific to your machine.
> Therefore I will close this issue for now. If you have anything to add or questions related to this problem just reply here and I will reopen it again

Just to Update: Yes its really strange. I updated my Server from 16.04 to 18.04 and also reinstalled Docker fresh with purged all Container, Images, Configs but i still havn't got it to run. So its quite Strange. On the other Side i made a fresh Install Ubuntu 18.04 and Docker and it worked Perfect!

Thanks for your Work. Eventually i will find some time to give a helping Hand with a Pull Request or so.

**Comment by grimsi** [comment] 2019-05-24 08:56
Thanks for the update and im glad that you could get it to work on a fresh installation :)

**Comment by HendrikRoth** [comment] 2019-06-03 17:33
Tried today to install accservermanager again and had the same issue.

here the error log:


```

**Comment by grimsi** [comment] 2019-06-05 11:21
The software is failing to deploy a container (NULL pointer exception). Currently I'm on a business trip until friday but I will try to take a look at it.
My current guess is that my application has problems connecting to your docker deamon, unfortunately I cant spot a docker error message in the logs. Do you have any software installed that could possibly interfere with docker or sockets?

**Comment by HendrikRoth** [comment] 2019-06-05 16:42
i manage the server via portainer (portainer.io) - but should not be a problem.

**Comment by HendrikRoth** [comment] 2019-06-08 14:34
in the log of the first run of accservermanager i found this log:

![Screenshot 2019-06-08 at 16 29 04](https://user-images.githubusercontent.com/68462/59148600-447fa480-8a0b-11e9-9fcd-04a35561dbf2.png)

**Comment by grimsi** [comment] 2019-06-08 14:55
Nice find didn't know how I couldn't see it.Looks like your firewall blocks docker from accessing docker hub and pulling the image. I will include a check in my software so I doesn't just crash when this happensAm 08.06.2019 16:34 schrieb Hendrik Roth <notifications@github.com>:in the log of the first run of accservermanager i found this log:

**Comment by HendrikRoth** [comment] 2019-06-08 14:56
removed my message because the problem occured because of missing linking docker.socket (creating server error still exists)

**Comment by HendrikRoth** [comment] 2019-06-08 21:58
starting your grimsi/accserver package manually works fine. seams really to be a problem with the manager starting/accessing docker maybe.

**Comment by grimsi** [comment] 2019-06-10 08:58
Okay I will close this issue again since you opened a dedicated issue for your problem. Lets use this new issue and try to sort it out

**Closed by grimsi** 2019-06-10 08:58 UTC
Labels: 3rd party, bug
